### ISSUE TITLE
Error showing during NPM of Okta-Hosted-Login

### ISSUE THREAD

**Issue by bretterer** [okta/samples-js-react#21] opened 2018-02-09 20:23 UTC
Just FYI.  there is an error showing during the npm install of the Okta-Hosted-Login

Terminal output
```
git clone git@github.com:okta/samples-js-react.git
Cloning into 'samples-js-react'...
remote: Counting objects: 474, done.
remote: Compressing objects: 100% (42/42), done.
remote: Total 474 (delta 25), reused 20 (delta 12), pack-reused 420
Receiving objects: 100% (474/474), 2.20 MiB | 1.54 MiB/s, done.
Resolving deltas: 100% (214/214), done.
➜  Code cd samples-js-react/okta-hosted-login
➜  okta-hosted-login git:(master) npm install

> fsevents@1.1.2 install /Users/bretterer/Code/samples-js-react/okta-hosted-login/node_modules/fsevents
> node install

node-pre-gyp ERR! Tried to download(404): https://fsevents-binaries.s3-us-west-2.amazonaws.com/v1.1.2/fse-v1.1.2-node-v59-darwin-x64.tar.gz
node-pre-gyp ERR! Pre-built binaries not found for fsevents@1.1.2 and node@9.5.0 (node-v59 ABI) (falling back to source compile with node-gyp)
  SOLINK_MODULE(target) Release/.node
  CXX(target) Release/obj.target/fse/fsevents.o
  SOLINK_MODULE(target) Release/fse.node
  COPY /Users/bretterer/Code/samples-js-react/okta-hosted-login/node_modules/fsevents/lib/binding/Release/node-v59-darwin-x64/fse.node
  TOUCH Release/obj.target/action_after_build.stamp

> uglifyjs-webpack-plugin@0.4.6 postinstall /Users/bretterer/Code/samples-js-react/okta-hosted-login/node_modules/uglifyjs-webpack-plugin
> node lib/post_install.js


> samples-js-react@0.1.0 postinstall /Users/bretterer/Code/samples-js-react/okta-hosted-login
> node post-install.js

Creating default configuration file..

Sample project is ready to go!  Please add your configuration to src/.samples.config.js, see the README for instructions.

added 1293 packages in 36.88s
```

NPM version: 5.6.0
Node Version: v9.5.0

**Comment by robertjd** [comment] 2018-02-09 21:00
What's your arch/OS?

**Comment by bretterer** [comment] 2018-02-09 21:02
os: High Sierra 10.13.2

**Comment by robertjd** [comment] 2018-02-09 21:20
FYI that this only appears to be a problem in Node 9, version 8 is okay.  In either version the sample can run, this is appears to be related to a dev dependency.

**Comment by jon-rtr** [comment] 2019-10-14 03:37
I'm seeing the same issue with `yarn install`.

*Node:* v12.12.0
*NPM:* 6.11.3
*Yarn:* 1.19.1

```
> fsevents@1.2.4 install /Users/jkaczynski/Projects/github/okta/samples-js-react/custom-login/node_modules/fsevents
> node install

node-pre-gyp WARN Tried to download(404): https://fsevents-binaries.s3-us-west-2.amazonaws.com/v1.2.4/fse-v1.2.4-node-v72-darwin-x64.tar.gz
node-pre-gyp WARN Pre-built binaries not found for fsevents@1.2.4 and node@12.12.0 (node-v72 ABI, unknown) (falling back to source compile with node-gyp)
  SOLINK_MODULE(target) Release/.node
  CXX(target) Release/obj.target/fse/fsevents.o
In file included from ../fsevents.cc:6:
In file included from ../../nan/nan.h:221:
In file included from ../../nan/nan_converters.h:67:
../../nan/nan_converters_43_inl.h:22:1: warning: 'ToBoolean' is deprecated: ToBoolean can never throw. Use Local version. [-Wdeprecated-declarations]
X(Boolean)
^
../../nan/nan_converters_43_inl.h:18:12: note: expanded from macro 'X'
      val->To ## TYPE(isolate->GetCurrentContext())                            \
           ^
<scratch space>:145:1: note: expanded from here
ToBoolean
^
/Users/jkaczynski/Library/Caches/node-gyp/12.12.0/include/node/v8.h:2567:3: note: 'ToBoolean' has been explicitly marked deprecated here
```

The same issue appears with `npm install`:

```
node-pre-gyp ERR! Tried to download(404): https://fsevents-binaries.s3-us-west-2.amazonaws.com/v1.1.3/fse-v1.1.3-node-v72-darwin-x64.tar.gz
node-pre-gyp ERR! Pre-built binaries not found for fsevents@1.1.3 and node@12.12.0 (node-v72 ABI, unknown) (falling back to source compile with node-gyp)
node-pre-gyp ERR! Tried to download(undefined): https://fsevents-binaries.s3-us-west-2.amazonaws.com/v1.1.3/fse-v1.1.3-node-v72-darwin-x64.tar.gz
node-pre-gyp ERR! Pre-built binaries not found for fsevents@1.1.3 and node@12.12.0 (node-v72 ABI, unknown) (falling back to source compile with node-gyp)
  SOLINK_MODULE(target) Release/.node
  SOLINK_MODULE(target) Release/.node
  CXX(target) Release/obj.target/fse/fsevents.o
  CXX(target) Release/obj.target/fse/fsevents.o
In file included from ../fsevents.cc:6:
In file included from ../../nan/nan.h:202:
In file included from ../../nan/nan_converters.h:67:
In file included from ../fsevents.cc:6:
In file included from ../../nan/nan.h:202:
In file included from ../../nan/nan_converters.h:67:
../../nan/nan_converters_43_inl.h:22:1: warning: 'ToBoolean' is ../../nan/nan_converters_43_inl.h:22:1: warning: 'ToBoolean' is deprecated: ToBoolean candeprecated:  neverToBoolean  throw. canUse Local version. [-Wdeprecated-declarations]
 never throw. Use Local version. [-Wdeprecated-declarations]
X(Boolean)
^
```

**Comment by swiftone** [comment] 2019-10-14 20:27
Hi @jon-rtr - Thanks for the report - as mentioned in the comment above, this is an expected part of the build process - if a pre-built version of the dependency doesn't exist, one is built on the spot.  That build process might have warnings or errors, and if the module is optional it might even fail to compile at all.

Unless this is preventing you from running the samples, this isn't considered an error.  Are you having any problems with the functionality of the samples?

**Comment by swiftone** [comment] 2019-10-28 20:02
Closing as "working as intended".  If this error is preventing you from running the samples, please feel free to reopen with details.

**Closed by swiftone** 2019-10-28 20:02 UTC
