### ISSUE TITLE
okta logout fails

### ISSUE THREAD

**Issue by Yasinjama** [okta/samples-js-react#25] opened 2018-03-01 21:29 UTC
I pulled the sample applications project, tried out the okta-hosted-login. I was able to login successfully, but when I clicked on the logout button it doesn't log me out. 

**Unhandled Rejection (AuthApiError): Not found: Resource not found: me (Session).**

It seems to be failing on the /api/v1/session/me call to destroy the session, the session is not found.

I was not getting this logout issue before.

**Comment by robertjd** [comment] 2018-03-02 21:43
Hi @Yasinjama , are you seeing a 404 when the library tries to make the DELETE call to /api/v1/session/me ?

**Comment by Yasinjama** [comment] 2018-03-03 05:25
Yes, that is correct.

**Comment by Sara3** [comment] 2018-05-14 23:37
When trying to log out (this.props.auth.logout()), if the session has expired or deleted. We get a 404 error on this call. 

DELETE https://johndeere.oktapreview.com/api/v1/sessions/me 404 (Not Found)
And here is the stack-trace I can see on browser console -

asyncToGenerator.js:20 Uncaught (in promise) AuthApiError {name: "AuthApiError", message: "Not found: Resource not found: me (Session)", errorSummary: "Not found: Resource not found: me (Session)", errorCode: "E0000007", errorLink: "E0000007", ...}
step @ asyncToGenerator.js:20
(anonymous) @ asyncToGenerator.js:30
Promise.then (async)
step @ asyncToGenerator.js:27

It gives an error instead of redirecting. Is this the same problem you are facing @jakehockey10 @Yasinjama

**Comment by Yasinjama** [comment] 2018-05-15 16:34
@Sara3 Yea that's the same problem I am facing. I had to find a work around for this by calling okta ${baseUrl}/v1/logout https://developer.okta.com/docs/api/resources/oidc#logout.

**Comment by scienced** [comment] 2018-05-28 09:31
I'm getting the same error (as @Sara3) using the okta code for VUE, any updates on how to fix this?

**Comment by Sara3** [comment] 2018-05-29 21:38
@scienced  I just did a PR. 
In Navbar.js I added a promise in "async logout()". It catches the error and redirects back to the login page. Here how my function will look like: 
`async logout() {
    let loginRedirect = this.login
    // Redirect to '/' after logout
    //if session is active
    this.props.auth.logout('/')
    .then(function (out){
      console.log("session is deleted");
    })
    .catch(function (error) {
      //if session is inactive
      loginRedirect();
    })
  }`

**Comment by rodoabad** [comment] 2018-07-12 01:09
@Sara3 I don't think that's the correct solution. You're pretty much going back to the user login if the user wanted to logout and be directed somewhere else (if possible).

**Comment by GunslingerBara** [comment] 2018-09-19 14:05
Any updates on this? I'm also experiencing this issue.

**Comment by rodoabad** [comment] 2018-09-21 12:48
cc @manueltanzi-okta for visibility!

**Comment by bjrosas** [comment] 2018-11-13 05:44
I am using vue and the sign in widget. I am also getting a 404 when accessing /api/v1/sessions/me when attempting to log out:

errorCode: "E0000007"
errorId: "oae-K6ey5u8RfK7nSpcwsV06A"
errorLink: "E0000007"
errorSummary: "Not found: Resource not found: me (Session)"
message: "Not found: Resource not found: me (Session)"
name: "AuthApiError"

**Comment by amputek** [comment] 2019-02-04 11:09
+1. This is still an issue..
`this.$auth.logout()` fails.

DELETE https://xxxxxxx.oktapreview.com/api/v1/sessions/me 404

errorCauses: []
errorCode: "E0000007"
errorId: "oae1WrE7cYRSk67HDn6dGBuoQ"
errorLink: "E0000007"
errorSummary: "Not found: Resource not found: me (Session)"
message: "Not found: Resource not found: me (Session)"
name: "AuthApiError"

**Comment by swiftone** [comment] 2019-02-05 21:20
We're reviewing the samples to make sure they are up to date with all changes, but it will take some time to get through all of them.

**Comment by jptacek** [comment] 2019-03-27 19:42
I believe the issue is due to blocking third party cookies. If I run the code as identified above, I am seeing the 404 error highlighted above. In Chrome (my daily driver) I block Third Party Cookies and have the issue. I tried running with Safari and it worked. Hopped back into Chrome and disabled blocking of third party cookies (aka back to default Chrome behavior) and it worked. Blocked them again and we are back to error.

Not sure if there are other issues with this too. Now I a bit stumped about what to do next. I am a bit of an edge case I assume, but for sure not the only one.

**Comment by swiftone** [comment] 2019-03-29 20:29
@jptacek - you are not the only one, but this is an edge case.  We're still gathering details so I don't want to give you incomplete information.  However it definitely is connected to 3rd party cookies (because Okta is 3rd party)

**Comment by swiftone** [comment] 2019-03-29 20:41
This is the same root cause as https://github.com/okta/okta-oidc-js/issues/200  ( as identified by @jptacek , thanks!) - closing this issue to track it all there.

**Closed by swiftone** 2019-03-29 20:41 UTC
